apiVersion: v1
kind: Pod
metadata:
  name: apigw
  labels:
    app: apigw
spec:
  containers:
    - name: apigw
      image: filestoreserver/apigw
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: svc-apigw
spec:
  type:
    NodePort
  selector:
    app: apigw
  ports:
    - name: http
      protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 9090