apiVersion: v1
kind: Pod
metadata:
  name: download
  labels:
    app: download
spec:
  containers:
    - name: download
      image: filestoreserver/download
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 38080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-download
spec:
  type:
    NodePort
  selector:
    app: download
  ports:
    - name: http-download
      protocol: TCP
      port: 81
      nodePort: 30081
      targetPort: 38080