apiVersion: v1
kind: Pod
metadata:
  name: upload
  labels:
    app: upload
spec:
  containers:
    - name: upload
      image: filestoreserver/upload
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 28080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-upload
spec:
  type:
    NodePort
  selector:
    app: upload
  ports:
    - name: http-upload
      protocol: TCP
      port: 82
      nodePort: 30082
      targetPort: 28080