// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: download.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DownloadService service

func NewDownloadServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DownloadService service

type DownloadService interface {
	DownloadEntry(ctx context.Context, in *ReqDownloadEntry, opts ...client.CallOption) (*RespDownloadEntry, error)
	DownloadURL(ctx context.Context, in *ReqDownloadURL, opts ...client.CallOption) (*RespDownloadURL, error)
}

type downloadService struct {
	c    client.Client
	name string
}

func NewDownloadService(name string, c client.Client) DownloadService {
	return &downloadService{
		c:    c,
		name: name,
	}
}

func (c *downloadService) DownloadEntry(ctx context.Context, in *ReqDownloadEntry, opts ...client.CallOption) (*RespDownloadEntry, error) {
	req := c.c.NewRequest(c.name, "DownloadService.DownloadEntry", in)
	out := new(RespDownloadEntry)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) DownloadURL(ctx context.Context, in *ReqDownloadURL, opts ...client.CallOption) (*RespDownloadURL, error) {
	req := c.c.NewRequest(c.name, "DownloadService.DownloadURL", in)
	out := new(RespDownloadURL)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DownloadService service

type DownloadServiceHandler interface {
	DownloadEntry(context.Context, *ReqDownloadEntry, *RespDownloadEntry) error
	DownloadURL(context.Context, *ReqDownloadURL, *RespDownloadURL) error
}

func RegisterDownloadServiceHandler(s server.Server, hdlr DownloadServiceHandler, opts ...server.HandlerOption) error {
	type downloadService interface {
		DownloadEntry(ctx context.Context, in *ReqDownloadEntry, out *RespDownloadEntry) error
		DownloadURL(ctx context.Context, in *ReqDownloadURL, out *RespDownloadURL) error
	}
	type DownloadService struct {
		downloadService
	}
	h := &downloadServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DownloadService{h}, opts...))
}

type downloadServiceHandler struct {
	DownloadServiceHandler
}

func (h *downloadServiceHandler) DownloadEntry(ctx context.Context, in *ReqDownloadEntry, out *RespDownloadEntry) error {
	return h.DownloadServiceHandler.DownloadEntry(ctx, in, out)
}

func (h *downloadServiceHandler) DownloadURL(ctx context.Context, in *ReqDownloadURL, out *RespDownloadURL) error {
	return h.DownloadServiceHandler.DownloadURL(ctx, in, out)
}
